version: "2"

services:
  # https://docs.docker.com/docker-hub/builds/automated-testing/
  sut:
    build:
      context: ./test
      dockerfile: Dockerfile
    depends_on:
      - dolibarr_db
      - dolibarr
      - dolibarr_nginx
    volumes_from:
      - dolibarr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - DOLI_TEST_HOSTNAME=dolibarr_nginx
      - DOLI_DB_NAME=${DOLIBARR_DB_NAME}
      - DOLI_DB_USER=${DOLIBARR_DB_USER}
      - DOLI_DB_PASSWORD=${DOLIBARR_DB_PASSWORD}

  dolibarr:
    build:
      context: ./
      dockerfile: Dockerfile
      args: 
        - TAG=${TAG}
        - VCS_REF=${VCS_REF}
        - BUILD_DATE=${BUILD_DATE}
    image: ${IMAGE_NAME}
    container_name: dolibarr
    #restart: always
    depends_on:
      - dolibarr_db
    links:
      - dolibarr_db
    ports:
      - 9000:9000
    volumes:
      - /srv/dolibarr/html:/var/www/html
      - /srv/dolibarr/documents:/var/www/documents
      - /srv/dolibarr/scripts:/var/www/scripts
    environment:
      - DOLI_DB_TYPE=pgsql
      - DOLI_DB_HOST=dolibarr_db # same as pgsql container name
      - DOLI_DB_PORT=5432
      - DOLI_DB_NAME=${DOLIBARR_DB_NAME}
      - DOLI_DB_USER=${DOLIBARR_DB_USER}
      - DOLI_DB_PASSWORD=${DOLIBARR_DB_PASSWORD}

  dolibarr_db:
    image: postgres:latest
    container_name: dolibarr_db
    #restart: always
    ports:
      - 5432:5432
    volumes:
      - /srv/dolibarr/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DOLIBARR_DB_NAME}
      - POSTGRES_USER=${DOLIBARR_DB_USER}
      - POSTGRES_PASSWORD=${DOLIBARR_DB_PASSWORD}

  dolibarr_nginx:
    image: nginx:latest
    container_name: dolibarr_nginx
    #restart: always
    ports:
      - 80:80
      # If you need SSL connection
      # - '443:443'
    depends_on:
      - dolibarr
    links:
      - dolibarr
    volumes:
      - /srv/dolibarr/html:/var/www/html
      # Provide a custom nginx conf
      #- ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # If you need SSL connection, you can provide your own certificates
      # - ./certs:/etc/letsencrypt
      # - ./certs-data:/data/letsencrypt
    environment:
      - NGINX_HOST=localhost # set your local domain or your live domain
      # - NGINX_CGI=dolibarr:9000 # same as dolibarr container name
