version: "2"

services:
  dolibarr:
    #image: dolibarr/docker-dolibarr:fpm
    #image: dolibarr/docker-dolibarr:alpine
    build: ./
    container_name: dolibarr
    #restart: always
    depends_on:
      - dolibarrdb
    links:
      - dolibarrdb
    ports:
      - 9000:9000
    volumes:
      - /srv/dolibarr/html:/var/www/html
      - /srv/dolibarr/documents:/var/www/documents
      - /srv/dolibarr/scripts:/var/www/scripts
    environment:
      - DOLI_DB_TYPE=pgsql
      - DOLI_DB_HOST=dolibarrdb # same as pgsql container name
      - DOLI_DB_PORT=5432
      - DOLI_DB_NAME=dolibarr # same as pgsql POSTGRES_DB env name
      - DOLI_DB_USER=dolibarr # same as pgsql POSTGRES_USER env name
      - DOLI_DB_PASSWORD=dolibarr # same as pgsql POSTGRES_PASSWORD env name

  dolibarrdb:
    image: postgres:latest
    container_name: dolibarrdb
    #restart: always
    ports:
      - 5432:5432
    volumes:
      - /srv/dolibarr/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dolibarr
      - POSTGRES_USER=dolibarr
      - POSTGRES_PASSWORD=dolibarr

  dolinginx:
    image: nginx:latest
    container_name: dolibarrnginx
    #restart: always
    ports:
      - 80:80
      # If you need SSL connection
      # - '443:443'
    depends_on:
      - dolibarr
    links:
      - dolibarr
    volumes:
      - /srv/dolibarr/html:/var/www/html
      # Provide a custom nginx conf
      #- ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # If you need SSL connection, you can provide your own certificates
      # - ./certs:/etc/letsencrypt
      # - ./certs-data:/data/letsencrypt
    environment:
      - NGINX_HOST=localhost # set your local domain or your live domain
      # - NGINX_CGI=dolibarr:9000 # same as dolibarr container name
