#!/bin/bash

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/

if [ -n "${DOCKER_PASSWORD}" ] && [ -n "${DOCKER_REGISTRY}" ]; then
    echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_LOGIN}" --password-stdin "${DOCKER_REGISTRY}"
fi
