#!/bin/bash

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/

if [ -f ./.dockertags ]; then
    for tag in $(cat ./.dockertags); do
        if [ ! "${tag}" = "${DOCKER_TAG}" ]; then
            docker buildx build \
            --build-arg "VCS_REF=$(git rev-parse --short HEAD)" \
            --build-arg "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
            --platform "$DOCKER_PLATFORM" \
            --push \
            -f "$DOCKERFILE_PATH" \
            -t "$DOCKER_REPO:$tag" .
        fi
    done
fi

if [ -n "${DOCKER_PASSWORD}" ] && [ -n "${DOCKER_REGISTRY}" ]; then
    docker logout "${DOCKER_REGISTRY}"
fi
