version: "2.3"

volumes:
  db:
  data:
  documents:
  scripts:

services:
  # https://docs.docker.com/docker-hub/builds/automated-testing/
  sut:
    build:
      context: ./test
      dockerfile: Dockerfile
    depends_on:
      - dolibarr
      - dolibarr_nginx
    volumes_from:
      - dolibarr
    volumes:
      - data:/var/www/html
      - documents:/var/www/documents
      - scripts:/var/www/scripts
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - DOCKER_TEST_CONTAINER=dolibarr
      - DOCKER_WEB_CONTAINER=dolibarr_nginx
      - DOLI_DB_NAME=${DOLIBARR_DB_NAME}
      - DOLI_DB_USER=${DOLIBARR_DB_USER}
      - DOLI_DB_PASSWORD=${DOLIBARR_DB_PASSWORD}

  dolibarr:
    build:
      context: ./
      dockerfile: Dockerfile
      args: 
        - TAG=${TAG}
        - VCS_REF=${VCS_REF}
        - BUILD_DATE=${BUILD_DATE}
    image: ${IMAGE_NAME}
    container_name: dolibarr
    #restart: always
    depends_on:
      dolibarr_db:
        condition: service_healthy
    links:
      - dolibarr_db
    expose:
      - "9000"
    #ports:
    #  - "9090:9000"
    volumes:
      - data:/var/www/html
      - documents:/var/www/documents
      - scripts:/var/www/scripts
      #- /srv/dolibarr/html:/var/www/html
      #- /srv/dolibarr/documents:/var/www/documents
      #- /srv/dolibarr/scripts:/var/www/scripts
    environment:
      - DOLI_DB_TYPE=pgsql
      - DOLI_DB_HOST=dolibarr_db # same as pgsql container name
      - DOLI_DB_PORT=5432
      - DOLI_DB_NAME=${DOLIBARR_DB_NAME}
      - DOLI_DB_USER=${DOLIBARR_DB_USER}
      - DOLI_DB_PASSWORD=${DOLIBARR_DB_PASSWORD}

  dolibarr_db:
    image: postgres:latest
    container_name: dolibarr_db
    #restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DOLIBARR_DB_USER}", "-d", "${DOLIBARR_DB_PASSWORD}"]
      interval: 60s
      retries: 5
      #start-period: 10s
    mem_limit: 256M
    memswap_limit: 256M
    expose:
      - "5432"
    #ports:
    #  - "55432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      #- /srv/dolibarr/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DOLIBARR_DB_NAME}
      - POSTGRES_USER=${DOLIBARR_DB_USER}
      - POSTGRES_PASSWORD=${DOLIBARR_DB_PASSWORD}

  dolibarr_nginx:
    image: nginx:latest
    container_name: dolibarr_nginx
    #restart: always
    expose:
      - "80"
    #ports:
    #  - "8080:80"
    #  # If you need SSL connection
    #  - "8443:443"
    depends_on:
      - dolibarr
    links:
      - dolibarr
    volumes:
      - data:/var/www/html
      #- /srv/dolibarr/html:/var/www/html
      - ./nginx/templates:/etc/nginx/templates
      # Provide a custom nginx conf
      #- ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # If you need SSL connection, you can provide your own certificates
      # - ./certs:/etc/letsencrypt
      # - ./certs-data:/data/letsencrypt
    environment:
      - NGINX_HOST=localhost # set your local domain or your live domain
      - NGINX_PHP_CGI=dolibarr:9000 # same as dolibarr container name

  dolibarr_mailer:
    image: sj26/mailcatcher:latest
    hostname: dolibarr_mailer
    container_name: dolibarr_mailer
    restart: always
    expose:
      - 1025
    ports:
      - "1025:1025"
      - "1080:1080"
    # If you want, you can sync time & timezone with host
    #volumes:
    #  - /etc/localtime:/etc/localtime:ro
    #  - /etc/timezone:/etc/timezone:ro
