
name: Docker Image CI

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['develop', '11.0', '12.0', '13.0', '14.0', '15.0', '16.0', ]
        php: ['7.3']
        archi: ['amd64', 'i386']
        variant: ['apache', 'fpm', 'fpm-alpine']

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Execute CI build hooks
        id: docker_build
        run: |
          cd images/${{ matrix.version }}/php${{ matrix.php }}-${{ matrix.variant }}-${{ matrix.archi }}
          # Export variables to tag against GitHub Container Registry
          #export DOCKER_REGISTRY=ghcr.io
          #export DOCKER_REPO=${{ github.repository }}
          ./hooks/run build

      - name: Display docker images
        run: docker images

      - name: Execute CI test hooks
        id: docker_test
        run: |
          ./hooks/run test

      #- name: Execute CI push hooks
      #  id: docker_push
      #  run: |
      #    # Export variables to login and push to GitHub Container Registry
      #    #export DOCKER_REGISTRY=ghcr.io
      #    #export DOCKER_LOGIN=${{ github.repository_owner }}
      #    #export DOCKER_PASSWORD=${{ secrets.GITHUB_REGISTRY_TOKEN }}
      #    ./hooks/run push
